name: mightyweb
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #BASE
  nb_utils: ^5.0.8
  google_fonts: ^5.0.0

  #UI
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.2.0
  package_info_plus: ^4.0.2
  flutter_speed_dial: ^7.0.0

  #STATE MANAGEMENT
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5

  #STORAGE & PERMISSION
  permission_handler: ^10.3.0
  path_provider: ^2.0.15
  provider: ^6.0.5

  #CONNECTIVITY
  http: ^1.0.0
  share_plus: ^7.0.2
  url_launcher: ^6.1.11
  store_redirect: ^2.0.1

  #Firebase
  firebase_in_app_messaging: ^0.7.3+3
  firebase_messaging: ^14.6.3
  firebase_core: ^2.14.0

  # PUSH NOTIFICATION
  onesignal_flutter: ^3.5.1

  # ADS
  google_mobile_ads: ^3.0.0
  facebook_audience_network: ^1.0.1

  # WEB TOOLS
  flutter_inappwebview: ^5.7.2+3

  qr_code_scanner: ^1.0.1

  flutter_localizations:
    sdk: flutter

dependency_overrides:
  flutter_cache_manager: ^3.3.0
  http: ^1.0.0

dev_dependencies:
  
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5
  mobx_codegen: ^2.3.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - assets/
    - lang/
